// <auto-generated />
namespace ReclutamientoSeleccionApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class creandodependenciaenempleadodecandidato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creandodependenciaenempleadodecandidato));
        
        string IMigrationMetadata.Id
        {
            get { return "202002082336375_creando dependencia en empleado de candidato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
