// <auto-generated />
namespace ReclutamientoSeleccionApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rollbackalmigrationanterior : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rollbackalmigrationanterior));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261517383_rollback al migration anterior"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
